sudo: false
language: ruby
dist: trusty
cache:
  bundler: true
before_install:
  - "gem install bundler --pre"
  - "bundler -v"
rvm:
  - 2.4.2
env:
  matrix:
    - SOLIDUS_BRANCH=v2.4
    - SOLIDUS_BRANCH=v2.5
    - SOLIDUS_BRANCH=v2.6
    - SOLIDUS_BRANCH=v2.7
    - SOLIDUS_BRANCH=v2.8
    - SOLIDUS_BRANCH=master
